// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Firebase Console > Project Settings > Web App'ten gerçek değerlerle güncelleyin.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADt9VvZKfuUZR-8JbgXQtikSxs7VnyP-Y',
    appId: '1:454457021902:web:77177f7a9ac8f123e0479f',
    messagingSenderId: '454457021902',
    projectId: 'tcr-app-c73ee',
    authDomain: 'tcr-app-c73ee.firebaseapp.com',
    storageBucket: 'tcr-app-c73ee.firebasestorage.app',
    measurementId: 'G-T9FKZQWQ95',
  );

  // 'flutterfire configure --platforms=web' ile otomatik oluşturulabilir.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEW-LZyGzeq5J2T-bu5WT1ycaEptG0yhA',
    appId: '1:454457021902:android:efefe2101d693028e0479f',
    messagingSenderId: '454457021902',
    projectId: 'tcr-app-c73ee',
    storageBucket: 'tcr-app-c73ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHyQ2jCrvL1JV1iWUMjPNDgHWnVr2QWmQ',
    appId: '1:454457021902:ios:e354e0077665c56be0479f',
    messagingSenderId: '454457021902',
    projectId: 'tcr-app-c73ee',
    storageBucket: 'tcr-app-c73ee.firebasestorage.app',
    iosBundleId: 'com.rivlus.projectTcr',
  );
}